<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ModulithFoundry.Samples.Wholesale.Inventory</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../src/Rootbolt.Auditing/Rootbolt.Auditing.EntityFrameworkCore.Postgres/Rootbolt.Auditing.EntityFrameworkCore.Postgres.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.ActorIdentity/Rootbolt.ActorIdentity/Rootbolt.ActorIdentity.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.Messaging/Rootbolt.Messaging.EntityFrameworkCore.Postgres/Rootbolt.Messaging.EntityFrameworkCore.Postgres.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.EventSourcing/Rootbolt.EventSourcing/Rootbolt.EventSourcing.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="../Inventory.Contracts/Inventory.Contracts.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.Tenancy/Rootbolt.Tenancy/Rootbolt.Tenancy.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.Persistence/Rootbolt.Persistence.EntityFrameworkCore/Rootbolt.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.Events/Rootbolt.Events.Serialization/Rootbolt.Events.Serialization.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.Events/Rootbolt.Events.History/Rootbolt.Events.History.csproj" />
    <ProjectReference Include="../../../../../src/Rootbolt.EventSourcing/Rootbolt.EventSourcing.EntityFrameworkCore/Rootbolt.EventSourcing.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
