// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Inventory;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20261008232958_AddTransactionalAudit")]
    partial class AddTransactionalAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationKey", "Id");

                    b.ToTable(
                        "event_streams",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint("positive_stream_version", "version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:RequiredInlineState:main:inventory.stock-position",
                            new[]
                            {
                                "inventory.stock-position",
                                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StoredEvent",
                                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StockPositionStateRow",
                            }
                        )
                        .HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StockPositionStateRow",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<JsonElement>("State").HasColumnType("jsonb").HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationKey", "StreamId");

                    b.ToTable(
                        "stock_position_current",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint(
                                "ck_stock_position_current_version",
                                "version > 0"
                            );
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StoredEvent",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("EventId").HasColumnType("uuid").HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_version");

                    b.HasKey("OrganizationKey", "EventId");

                    b.HasIndex("OrganizationKey", "StreamId", "StreamVersion").IsUnique();

                    b.ToTable(
                        "events",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint("positive_event_schema", "schema_version >= 1");

                            t.HasCheckConstraint("positive_event_version", "stream_version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "Sku").IsUnique();

                    b.ToTable("stock_availability", "inventory");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Auditing.EntityFrameworkCore.AuditRecord",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorKey").HasColumnType("text").HasColumnName("actor_key");

                    b.Property<int>("ActorKind")
                        .HasColumnType("integer")
                        .HasColumnName("actor_kind");
                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("InitiatorKey")
                        .HasColumnType("text")
                        .HasColumnName("initiator_key");

                    b.Property<int?>("InitiatorKind")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<string>("TenantKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_key");
                    b.HasKey("Id");

                    b.HasIndex("TenantKey", "SubjectType", "SubjectKey", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_subject_timeline");

                    b.ToTable("audit_entries", "inventory");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "TenantKey")
                        .HasAnnotation("Rootbolt:Audit", true);
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Messaging.EntityFrameworkCore.InboxMessageRecord",
                b =>
                {
                    b.Property<string>("SubscriptionKey")
                        .HasColumnType("text")
                        .HasColumnName("subscription_key");

                    b.Property<string>("ProducerKey")
                        .HasColumnType("text")
                        .HasColumnName("producer_key");

                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("TenantKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_key");

                    b.HasKey("SubscriptionKey", "ProducerKey", "MessageId");

                    b.HasIndex("SubscriptionKey", "AvailableAt", "ReceivedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable(
                        "inbox_messages",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint("ck_inbox_schema", "schema_version > 0");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "TenantKey")
                        .HasAnnotation("Rootbolt:Inbox", true)
                        .HasAnnotation("Rootbolt:InboxProvider", "Postgres");
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Messaging.EntityFrameworkCore.OutboxMessageRecord",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<long>("Attempts").HasColumnType("bigint").HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("TenantKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("owner_key");

                    b.HasKey("MessageId");

                    b.HasIndex("AvailableAt", "LeaseUntil", "MessageId")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable(
                        "outbox_messages",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempts", "attempts >= 0");

                            t.HasCheckConstraint(
                                "ck_outbox_lease",
                                "(lease_token IS NULL) = (lease_until IS NULL)"
                            );

                            t.HasCheckConstraint("ck_outbox_schema", "schema_version > 0");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "TenantKey")
                        .HasAnnotation("Rootbolt:Outbox", true)
                        .HasAnnotation("Rootbolt:OutboxProvider", "Postgres");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StockPositionStateRow",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StoredEvent",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
