// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Inventory;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Inventory.Migrations;

[DbContext(typeof(InventoryDbContext))]
[Migration("20261006135521_AddStockPositionCurrent")]
partial class AddStockPositionCurrent
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("inventory")
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
            b =>
            {
                b.Property<string>("OrganizationKey")
                    .IsConcurrencyToken()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("organization_key");

                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at");

                b.Property<string>("StreamType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("stream_type");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("updated_at");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("OrganizationKey", "Id");

                b.ToTable(
                    "event_streams",
                    "inventory",
                    t =>
                    {
                        t.HasCheckConstraint("positive_stream_version", "version >= 1");
                    }
                );

                b.HasAnnotation(
                        "ModulithFoundry:TenantContextMember",
                        "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                    )
                    .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                    .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "OrganizationKey");
            }
        );

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StockPositionCurrentRow",
            b =>
            {
                b.Property<string>("OrganizationKey")
                    .IsConcurrencyToken()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("organization_key");

                b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                b.Property<DateTimeOffset>("RecordedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at");

                b.Property<JsonElement>("State").HasColumnType("jsonb").HasColumnName("state");

                b.Property<long>("Version")
                    .IsConcurrencyToken()
                    .HasColumnType("bigint")
                    .HasColumnName("version");

                b.HasKey("OrganizationKey", "StreamId");

                b.ToTable(
                    "stock_position_current",
                    "inventory",
                    t =>
                    {
                        t.HasCheckConstraint("ck_stock_position_current_version", "version > 0");
                    }
                );

                b.HasAnnotation(
                        "ModulithFoundry:TenantContextMember",
                        "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                    )
                    .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                    .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "OrganizationKey");
            }
        );

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StoredEvent",
            b =>
            {
                b.Property<string>("OrganizationKey")
                    .IsConcurrencyToken()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("organization_key");

                b.Property<Guid>("EventId").HasColumnType("uuid").HasColumnName("event_id");

                b.Property<string>("EventName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("event_name");

                b.Property<JsonElement>("Payload").HasColumnType("jsonb").HasColumnName("payload");

                b.Property<DateTimeOffset>("RecordedAt")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("recorded_at");

                b.Property<int>("SchemaVersion")
                    .HasColumnType("integer")
                    .HasColumnName("schema_version");

                b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                b.Property<long>("StreamVersion")
                    .HasColumnType("bigint")
                    .HasColumnName("stream_version");

                b.HasKey("OrganizationKey", "EventId");

                b.HasIndex("OrganizationKey", "StreamId", "StreamVersion").IsUnique();

                b.ToTable(
                    "events",
                    "inventory",
                    t =>
                    {
                        t.HasCheckConstraint("positive_event_schema", "schema_version >= 1");

                        t.HasCheckConstraint("positive_event_version", "stream_version >= 1");
                    }
                );

                b.HasAnnotation(
                        "ModulithFoundry:TenantContextMember",
                        "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                    )
                    .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                    .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "OrganizationKey");
            }
        );

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockRow",
            b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                b.Property<int>("AvailableQuantity")
                    .HasColumnType("integer")
                    .HasColumnName("available_quantity");

                b.Property<string>("OrganizationKey")
                    .IsConcurrencyToken()
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("organization_key");

                b.Property<string>("Sku")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("sku");

                b.HasKey("Id");

                b.HasIndex("OrganizationKey", "Sku").IsUnique();

                b.ToTable("stock_availability", "inventory");

                b.HasAnnotation(
                        "ModulithFoundry:TenantContextMember",
                        "ModulithFoundry.Samples.Wholesale.Inventory.InventoryDbContext, Inventory, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                    )
                    .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                    .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "OrganizationKey");
            }
        );

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StockPositionCurrentRow",
            b =>
            {
                b.HasOne(
                        "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
                        null
                    )
                    .WithMany()
                    .HasForeignKey("OrganizationKey", "StreamId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            }
        );

        modelBuilder.Entity(
            "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.StoredEvent",
            b =>
            {
                b.HasOne(
                        "ModulithFoundry.Samples.Wholesale.Inventory.StockPositions.EventStream",
                        null
                    )
                    .WithMany()
                    .HasForeignKey("OrganizationKey", "StreamId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            }
        );
#pragma warning restore 612, 618
    }
}
