// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.PersistenceDemo.Sales;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.PersistenceDemo.Sales.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20261004154254_InitialSales")]
    partial class InitialSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.PersistenceDemo.Sales.CustomerReference",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");

                    b.Property<string>("Code").IsRequired().HasColumnType("text");

                    b.Property<string>("DisplayName").IsRequired().HasColumnType("text");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "Code").IsUnique();

                    b.ToTable("customer_reference", "sales");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.PersistenceDemo.Sales.SalesDbContext, PersistenceDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );
#pragma warning restore 612, 618
        }
    }
}
