// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.OutboxDemo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace OutboxDemo.Migrations
{
    [DbContext(typeof(ExportDbContext))]
    [Migration("20261008171519_InitialExports")]
    partial class InitialExports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.OutboxDemo.ExportRequest",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");

                    b.Property<int>("Pages").HasColumnType("integer");

                    b.Property<bool>("Submitted").HasColumnType("boolean");

                    b.Property<long>("Version").IsConcurrencyToken().HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("requests", "exports");
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Messaging.EntityFrameworkCore.OutboxMessageRecord",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<long>("Attempts").HasColumnType("bigint").HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("RouteKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("destination");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_name");

                    b.Property<string>("TenantKey")
                        .HasColumnType("text")
                        .HasColumnName("owner_key");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("QueuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("queued_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("MessageId");

                    b.HasIndex("AvailableAt", "LeaseUntil", "MessageId")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable(
                        "outgoing_work",
                        "exports",
                        t =>
                        {
                            t.HasCheckConstraint("ck_outbox_attempts", "attempts >= 0");

                            t.HasCheckConstraint(
                                "ck_outbox_lease",
                                "(lease_token IS NULL) = (lease_until IS NULL)"
                            );

                            t.HasCheckConstraint("ck_outbox_schema", "schema_version > 0");
                        }
                    );

                    b.HasAnnotation("Rootbolt:Outbox", true)
                        .HasAnnotation("Rootbolt:OutboxProvider", "Postgres");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
