// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Modules.Purchasing.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Modules.Purchasing.Persistence.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    [Migration("20261001211232_AddStockItemReferenceInbox")]
    partial class AddStockItemReferenceInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("purchasing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemBootstrapCheckpoint",
                b =>
                {
                    b.Property<int>("Id").HasColumnType("integer").HasColumnName("id");

                    b.Property<bool>("IsReady").HasColumnType("boolean").HasColumnName("is_ready");

                    b.Property<long?>("SnapshotWatermark")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_watermark");

                    b.HasKey("Id");

                    b.ToTable(
                        "stock_item_bootstrap",
                        "purchasing",
                        t =>
                        {
                            t.HasCheckConstraint("ck_stock_item_bootstrap_singleton", "id = 1");
                        }
                    );

                    b.HasData(new { Id = 1, IsReady = false });
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemReferenceProjection",
                b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.HasKey("OrganizationId", "StockItemId");

                    b.ToTable("stock_item_references", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemReferenceReceipt",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId");

                    b.ToTable("stock_item_reference_inbox", "purchasing");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
