// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.PersistenceDemo.Inventory;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.PersistenceDemo.Inventory.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20261004154157_InitialInventory")]
    partial class InitialInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.PersistenceDemo.Inventory.ReferenceCategory",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");

                    b.Property<string>("Name").IsRequired().HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("reference_category", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.PersistenceDemo.Inventory.StockReference",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");

                    b.Property<bool>("IsDeleted").HasColumnType("boolean");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity").HasColumnType("integer");

                    b.Property<string>("Sku").IsRequired().HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "Sku").IsUnique();

                    b.ToTable("stock_reference", "inventory");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.PersistenceDemo.Inventory.InventoryDbContext, PersistenceDemo, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );
#pragma warning restore 612, 618
        }
    }
}
