<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ModulithFoundry.Modules.Sales</AssemblyName>
    <RootNamespace>ModulithFoundry.Modules.Sales</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Sales.Contracts/Sales.Contracts.csproj" />
  </ItemGroup>
</Project>
