<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <ProjectReference Include="../AppHost/Wholesale.AppHost.csproj" />
    <ProjectReference Include="../HttpIdentityDemo/HttpIdentityDemo.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
