<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ModulithFoundry.Modules.Sales.Contracts</AssemblyName>
    <RootNamespace>ModulithFoundry.Modules.Sales.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../Access/Access.Contracts/Access.Contracts.csproj" />
    <ProjectReference Include="../../Inventory/Inventory.Contracts/Inventory.Contracts.csproj" />
  </ItemGroup>
</Project>
