<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ModulithFoundry.Samples.Wholesale.Purchasing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../src/ModulithFoundry.EventSourcing/ModulithFoundry.EventSourcing/ModulithFoundry.EventSourcing.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="../Purchasing.Contracts/Purchasing.Contracts.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Tenancy/ModulithFoundry.Tenancy/ModulithFoundry.Tenancy.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Persistence/ModulithFoundry.Persistence.EntityFrameworkCore/ModulithFoundry.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Events/ModulithFoundry.Events.Serialization/ModulithFoundry.Events.Serialization.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Events/ModulithFoundry.Events.History/ModulithFoundry.Events.History.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.EventSourcing/ModulithFoundry.EventSourcing.EntityFrameworkCore/ModulithFoundry.EventSourcing.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
