// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.InboxDemo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InboxDemo.Migrations
{
    [DbContext(typeof(RenderDbContext))]
    [Migration("20261008213953_InitialRendering")]
    partial class InitialRendering
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.InboxDemo.RenderJob",
                b =>
                {
                    b.Property<Guid>("ExportRequestId").HasColumnType("uuid");

                    b.Property<int>("Pages").HasColumnType("integer");

                    b.HasKey("ExportRequestId");

                    b.ToTable(
                        "jobs",
                        "rendering",
                        t =>
                        {
                            t.HasCheckConstraint("ck_job_pages", "\"Pages\" > 0");
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Messaging.EntityFrameworkCore.InboxMessageRecord",
                b =>
                {
                    b.Property<string>("SubscriptionKey")
                        .HasColumnType("text")
                        .HasColumnName("subscription_key");

                    b.Property<string>("ProducerKey")
                        .HasColumnType("text")
                        .HasColumnName("producer_key");

                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("MessageName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("clock_timestamp()");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("TenantKey")
                        .HasColumnType("text")
                        .HasColumnName("tenant_key");

                    b.HasKey("SubscriptionKey", "ProducerKey", "MessageId");

                    b.HasIndex("SubscriptionKey", "AvailableAt", "ReceivedAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable(
                        "incoming_work",
                        "rendering",
                        t =>
                        {
                            t.HasCheckConstraint("ck_inbox_schema", "schema_version > 0");
                        }
                    );

                    b.HasAnnotation("Rootbolt:Inbox", true)
                        .HasAnnotation("Rootbolt:InboxProvider", "Postgres");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
