<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OutboxDemo/OutboxDemo.csproj" />
    <ProjectReference Include="../InboxDemo/InboxDemo.csproj" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
</Project>
