// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Purchasing;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Purchasing.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    [Migration("20261007203326_RemoveLegacyPurchaseOrderSummary")]
    partial class RemoveLegacyPurchaseOrderSummary
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("purchasing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.EventStream",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationKey", "Id");

                    b.ToTable(
                        "event_streams",
                        "purchasing",
                        t =>
                        {
                            t.HasCheckConstraint("positive_stream_version", "version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:RequiredInlineState:main:purchasing.purchase-order",
                            new[]
                            {
                                "purchasing.purchase-order",
                                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.StoredEvent",
                                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.PurchaseOrderStateRow",
                            }
                        )
                        .HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Purchasing.PurchasingDbContext, Purchasing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.PurchaseOrderStateRow",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<JsonElement>("State").HasColumnType("jsonb").HasColumnName("state");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("OrganizationKey", "StreamId");

                    b.ToTable(
                        "purchase_order_current",
                        "purchasing",
                        t =>
                        {
                            t.HasCheckConstraint(
                                "ck_purchase_order_current_version",
                                "version > 0"
                            );
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Purchasing.PurchasingDbContext, Purchasing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.StoredEvent",
                b =>
                {
                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<Guid>("EventId").HasColumnType("uuid").HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_version");

                    b.HasKey("OrganizationKey", "EventId");

                    b.HasIndex("OrganizationKey", "StreamId", "StreamVersion").IsUnique();

                    b.ToTable(
                        "events",
                        "purchasing",
                        t =>
                        {
                            t.HasCheckConstraint("positive_event_schema", "schema_version >= 1");

                            t.HasCheckConstraint("positive_event_version", "stream_version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Purchasing.PurchasingDbContext, Purchasing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.PurchaseOrderStateRow",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.EventStream",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.StoredEvent",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Samples.Wholesale.Purchasing.PurchaseOrders.EventStream",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
