<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>ModulithFoundry.Samples.Wholesale.HttpIdentityDemo</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <ProjectReference Include="../../../src/ModulithFoundry.ActorIdentity.AspNetCore/ModulithFoundry.ActorIdentity.AspNetCore.csproj" />
    <ProjectReference Include="../../../src/ModulithFoundry.Tenancy.AspNetCore/ModulithFoundry.Tenancy.AspNetCore.csproj" />
    <ProjectReference Include="../modules/Access/Access/Access.csproj" />
    <ProjectReference Include="../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../modules/Sales/Sales/Sales.csproj" />
  </ItemGroup>
</Project>
