<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TngTech.ArchUnitNET.xUnitV3" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../apps/Api/ModulithFoundry.Api.csproj" />
    <ProjectReference Include="../../apps/AppHost/ModulithFoundry.AppHost.csproj" />
    <ProjectReference Include="../../apps/Migrator/ModulithFoundry.Migrator.csproj" />
    <ProjectReference Include="../../modules/Access/Access.Contracts/Access.Contracts.csproj" />
    <ProjectReference Include="../../modules/Access/Access/Access.csproj" />
    <ProjectReference Include="../../modules/Inventory/Inventory.Contracts/Inventory.Contracts.csproj" />
    <ProjectReference Include="../../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../../modules/Purchasing/Purchasing.Contracts/Purchasing.Contracts.csproj" />
    <ProjectReference Include="../../modules/Purchasing/Purchasing/Purchasing.csproj" />
    <ProjectReference Include="../../modules/Sales/Sales.Contracts/Sales.Contracts.csproj" />
    <ProjectReference Include="../../modules/Sales/Sales/Sales.csproj" />
    <ProjectReference Include="../../shared/ServiceDefaults/ModulithFoundry.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
