<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Rebus" />
    <ProjectReference Include="../../modules/Inventory/Inventory/Inventory.csproj" />
  </ItemGroup>
</Project>
