<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ModulithFoundry.Samples.Wholesale.Sales</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <ProjectReference Include="../Sales.Contracts/Sales.Contracts.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Tenancy/ModulithFoundry.Tenancy.csproj" />
    <ProjectReference Include="../../../../../src/ModulithFoundry.Persistence.EntityFrameworkCore/ModulithFoundry.Persistence.EntityFrameworkCore.csproj" />
  </ItemGroup>
</Project>
