// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Modules.Purchasing.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Modules.Purchasing.Persistence.Migrations
{
    [DbContext(typeof(PurchasingDbContext))]
    [Migration("20261002084755_AddReplenishmentRequests")]
    partial class AddReplenishmentRequests
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("purchasing")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.Audit.PurchasingAuditEntry",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.Property<Guid>("SubjectId").HasColumnType("uuid").HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.Property<string>("SystemActor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("system_actor");

                    b.HasKey("Id").HasName("pk_audit_entries");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_organization_occurred_at");

                    b.ToTable("audit_entries", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.Messaging.Persistence.PurchasingInboxReceipt",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<bool>("Rejected").HasColumnType("boolean").HasColumnName("rejected");

                    b.HasKey("MessageId").HasName("pk_inbox_receipts");

                    b.ToTable("inbox_receipts", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.Messaging.Persistence.PurchasingOutboxMessage",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<int>("Attempts").HasColumnType("integer").HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("message_type");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("MessageId").HasName("pk_outbox_messages");

                    b.HasIndex("AvailableAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_messages", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.Replenishment.ReplenishmentRequirement",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<long>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(
                        b.Property<long>("Number")
                    );

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("quantity");

                    b.Property<long>("ReferenceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_revision");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("Id").HasName("pk_requirements");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_requirements_operation");

                    b.HasIndex("OrganizationId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ux_requirements_organization_number");

                    b.ToTable("requirements", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.Replenishment.Requests.ReplenishmentRequest",
                b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("FirstMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_message_id");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<long>("MinimumReferenceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("minimum_reference_revision");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("order_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("ProcessId").HasColumnType("uuid").HasColumnName("process_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid")
                        .HasColumnName("requirement_id");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.HasKey("OperationId").HasName("pk_replenishment_requests");

                    b.HasIndex("NextAttemptAt")
                        .HasDatabaseName("ix_replenishment_requests_pending")
                        .HasFilter("requirement_id IS NULL AND reason_code IS NULL");

                    b.ToTable("replenishment_requests", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemBootstrapCheckpoint",
                b =>
                {
                    b.Property<int>("Id").HasColumnType("integer").HasColumnName("id");

                    b.Property<bool>("IsReady").HasColumnType("boolean").HasColumnName("is_ready");

                    b.Property<long?>("SnapshotWatermark")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_watermark");

                    b.HasKey("Id");

                    b.ToTable(
                        "stock_item_bootstrap",
                        "purchasing",
                        t =>
                        {
                            t.HasCheckConstraint("ck_stock_item_bootstrap_singleton", "id = 1");
                        }
                    );

                    b.HasData(new { Id = 1, IsReady = false });
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemReferenceProjection",
                b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<long>("SourceRevision")
                        .HasColumnType("bigint")
                        .HasColumnName("source_revision");

                    b.HasKey("OrganizationId", "StockItemId");

                    b.ToTable("stock_item_references", "purchasing");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Purchasing.StockItemProjection.Persistence.StockItemReferenceReceipt",
                b =>
                {
                    b.Property<Guid>("MessageId").HasColumnType("uuid").HasColumnName("message_id");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("fingerprint");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId");

                    b.ToTable("stock_item_reference_inbox", "purchasing");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
