// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Modules.Sales.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Modules.Sales.Persistence.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20261001121218_AddSalesApprovalAuthorities")]
    internal sealed partial class AddSalesApprovalAuthorities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.ApprovalAuthorities.SalesApprovalAuthority",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<decimal>("MaximumAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("maximum_amount");

                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id").HasName("pk_approval_authorities");

                    b.HasIndex("OrganizationId", "MembershipId")
                        .IsUnique()
                        .HasDatabaseName("ux_approval_authorities_organization_membership");

                    b.ToTable("approval_authorities", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Audit.SalesAuditEntry",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.Property<Guid>("SubjectId").HasColumnType("uuid").HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id").HasName("pk_audit_entries");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_organization_occurred_at");

                    b.ToTable("audit_entries", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Customers.Customer",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id").HasName("pk_customers");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_organization_code");

                    b.ToTable("customers", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Orders.Activity.SalesOrderActivity",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrderId").HasColumnType("uuid").HasColumnName("order_id");

                    b.Property<long>("OrderVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("order_version");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("Id").HasName("pk_order_activity");

                    b.HasIndex("OrderId");

                    b.HasIndex("OrganizationId", "OrderId", "OrderVersion")
                        .HasDatabaseName("ix_order_activity_organization_order_version");

                    b.ToTable("order_activity", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Orders.Persistence.SalesOrderNumber",
                b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<long>("LastNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_number");

                    b.HasKey("OrganizationId").HasName("pk_order_numbers");

                    b.ToTable("order_numbers", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Orders.SalesOrder",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("order_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<Guid?>("SubmittedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_by");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(19, 2)
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("total_amount");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id").HasName("pk_orders");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrganizationId", "OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_organization_number");

                    b.ToTable("orders", "sales");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Orders.Activity.SalesOrderActivity",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Sales.Orders.SalesOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_activity_orders");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Sales.Orders.SalesOrder",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Sales.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_customers");

                    b.OwnsMany(
                        "ModulithFoundry.Modules.Sales.Orders.SalesOrderLine",
                        "Lines",
                        b1 =>
                        {
                            b1.Property<Guid>("order_id").HasColumnType("uuid");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("integer")
                                .HasColumnName("line_number");

                            b1.Property<string>("BaseUnitCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("base_unit_code");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("description");

                            b1.Property<decimal>("LineAmount")
                                .HasPrecision(19, 2)
                                .HasColumnType("numeric(19,2)")
                                .HasColumnName("line_amount");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(19, 6)
                                .HasColumnType("numeric(19,6)")
                                .HasColumnName("quantity");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid")
                                .HasColumnName("stock_item_id");

                            b1.Property<decimal>("UnitPrice")
                                .HasPrecision(19, 4)
                                .HasColumnType("numeric(19,4)")
                                .HasColumnName("unit_price");

                            b1.HasKey("order_id", "LineNumber").HasName("pk_order_lines");

                            b1.ToTable("order_lines", "sales");

                            b1.WithOwner().HasForeignKey("order_id");
                        }
                    );

                    b.Navigation("Lines");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
