<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Rootbolt.Messaging/Rootbolt.Messaging.csproj" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
