<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OutboxDemo/OutboxDemo.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <Compile Include="../../tests/Support/PostgreSqlFixture.cs" Link="PostgreSqlFixture.cs" />
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
