<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Rebus" />
    <PackageReference Include="Rebus.RabbitMq" />
    <PackageReference Include="Rebus.ServiceProvider" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.RabbitMq" />
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../BrokerReceiver/BrokerReceiver.csproj" />
    <Using Include="Xunit" />
  </ItemGroup>
  <Target Name="CopyBrokerReceiverRuntimeFiles" AfterTargets="Build">
    <ItemGroup>
      <ReceiverRuntimeFile Include="../BrokerReceiver/bin/$(Configuration)/$(TargetFramework)/BrokerReceiver.runtimeconfig.json" />
      <ReceiverRuntimeFile Include="../BrokerReceiver/bin/$(Configuration)/$(TargetFramework)/BrokerReceiver.deps.json" />
    </ItemGroup>
    <Copy SourceFiles="@(ReceiverRuntimeFile)" DestinationFolder="$(OutDir)" />
  </Target>
</Project>
