// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Modules.Inventory.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Modules.Inventory.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260930021241_AddStockPositions")]
    partial class AddStockPositions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.ReferenceData.InventoryAuditEntry",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.Property<Guid>("SubjectId").HasColumnType("uuid").HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id").HasName("pk_audit_entries");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_organization_occurred_at");

                    b.ToTable("audit_entries", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.ReferenceData.StockItems.StockItem",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id").HasName("pk_stock_items");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_stock_items_organization_active");

                    b.HasIndex("OrganizationId", "Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_items_organization_sku");

                    b.ToTable("stock_items", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.ReferenceData.StockingLocations.StockingLocation",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id").HasName("pk_stocking_locations");

                    b.HasIndex("OrganizationId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_stocking_locations_organization_code");

                    b.HasIndex("OrganizationId", "IsActive")
                        .HasDatabaseName("ix_stocking_locations_organization_active");

                    b.ToTable("stocking_locations", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.EventStream",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id").HasName("pk_event_streams");

                    b.HasIndex("OrganizationId", "StreamType")
                        .HasDatabaseName("ix_event_streams_organization_type");

                    b.ToTable("event_streams", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.StockPositionCurrent",
                b =>
                {
                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<decimal>("AvailableQuantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("available_quantity");

                    b.Property<string>("BaseUnitCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("base_unit_code");

                    b.Property<decimal>("OnHandQuantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("on_hand_quantity");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<decimal>("ReservedQuantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("reserved_quantity");

                    b.Property<Guid>("StockItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("stock_item_id");

                    b.Property<Guid>("StockingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("stocking_location_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version").HasColumnType("bigint").HasColumnName("version");

                    b.HasKey("StreamId").HasName("pk_stock_position_current");

                    b.HasIndex("OrganizationId", "StockingLocationId", "StockItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_stock_position_current_identity");

                    b.ToTable(
                        "stock_position_current",
                        "inventory",
                        t =>
                        {
                            t.HasCheckConstraint(
                                "ck_stock_position_current_non_negative",
                                "on_hand_quantity >= 0 AND reserved_quantity >= 0 AND available_quantity >= 0"
                            );

                            t.HasCheckConstraint(
                                "ck_stock_position_current_quantity_balance",
                                "reserved_quantity <= on_hand_quantity AND available_quantity = on_hand_quantity - reserved_quantity"
                            );
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.StoredEvent",
                b =>
                {
                    b.Property<Guid>("EventId").HasColumnType("uuid").HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<long>("GlobalSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("global_sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(
                        b.Property<long>("GlobalSequence")
                    );

                    b.Property<JsonElement>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_version");

                    b.HasKey("EventId").HasName("pk_events");

                    b.HasIndex("GlobalSequence")
                        .IsUnique()
                        .HasDatabaseName("ux_events_global_sequence");

                    b.HasIndex("OrganizationId", "RecordedAt")
                        .HasDatabaseName("ix_events_organization_recorded_at");

                    b.HasIndex("StreamId", "StreamVersion")
                        .IsUnique()
                        .HasDatabaseName("ux_events_stream_version");

                    b.ToTable("events", "inventory");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.StockPositionCurrent",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.EventStream",
                            null
                        )
                        .WithOne()
                        .HasForeignKey(
                            "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.StockPositionCurrent",
                            "StreamId"
                        )
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_position_current_event_streams_stream_id");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.StoredEvent",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Modules.Inventory.StockPositions.Persistence.EventStream",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_events_event_streams_stream_id");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
