<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
    <ProjectReference Include="../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../modules/Purchasing/Purchasing/Purchasing.csproj" />
    <None
      Include="../EventCodecDemo/Fixtures/**/*.json"
      Link="Fixtures/%(RecursiveDir)%(Filename)%(Extension)"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>
</Project>
