<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ModulithFoundry.Migrator</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../modules/Access/Access/Access.csproj" />
    <ProjectReference Include="../../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../../modules/Purchasing/Purchasing/Purchasing.csproj" />
    <ProjectReference Include="../../modules/Sales/Sales/Sales.csproj" />
    <ProjectReference Include="../../shared/ServiceDefaults/ModulithFoundry.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
