<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../modules/Sales/Sales/Sales.csproj" />
    <ProjectReference Include="../modules/Inventory/Inventory/Inventory.csproj" />
    <ProjectReference Include="../ServiceDefaults/Wholesale.ServiceDefaults.csproj" />
    <ProjectReference Include="../../../src/Rootbolt.Messaging/Rootbolt.Messaging.OpenTelemetry/Rootbolt.Messaging.OpenTelemetry.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>
</Project>
