// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Sales;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Sales.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.AddressRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address_line");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "CustomerId").IsUnique();

                    b.ToTable("customer_addresses", "sales");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Sales.SalesDbContext, Sales, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.CustomerRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "Code").IsUnique();

                    b.ToTable(
                        "customer_profiles",
                        "sales",
                        t =>
                        {
                            t.HasCheckConstraint("positive_version", "version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Sales.SalesDbContext, Sales, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "Rootbolt.Auditing.EntityFrameworkCore.AuditRecord",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorKey").HasColumnType("text").HasColumnName("actor_key");

                    b.Property<int>("ActorKind")
                        .HasColumnType("integer")
                        .HasColumnName("actor_kind");
                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<string>("InitiatorKey")
                        .HasColumnType("text")
                        .HasColumnName("initiator_key");

                    b.Property<int?>("InitiatorKind")
                        .HasColumnType("integer")
                        .HasColumnName("initiator_kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("reason_code");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SubjectKey")
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<string>("TenantKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_key");
                    b.HasKey("Id");

                    b.HasIndex("TenantKey", "SubjectType", "SubjectKey", "OccurredAt", "Id")
                        .HasDatabaseName("ix_audit_subject_timeline");

                    b.ToTable("audit_entries", "sales");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Sales.SalesDbContext, Sales, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "TenantKey")
                        .HasAnnotation("Rootbolt:Audit", true);
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.AddressRow",
                b =>
                {
                    b.HasOne("ModulithFoundry.Samples.Wholesale.Sales.CustomerRow", null)
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "CustomerId")
                        .HasPrincipalKey("OrganizationKey", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
