// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Sales;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Sales.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    partial class SalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sales")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.AddressRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("address_line");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "CustomerId").IsUnique();

                    b.ToTable("customer_addresses", "sales");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Sales.SalesDbContext, Sales, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.CustomerRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("OrganizationKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_key");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationKey", "Code").IsUnique();

                    b.ToTable(
                        "customer_profiles",
                        "sales",
                        t =>
                        {
                            t.HasCheckConstraint("positive_version", "version >= 1");
                        }
                    );

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ModulithFoundry.Samples.Wholesale.Sales.SalesDbContext, Sales, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredOrganizationKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "OrganizationScope")
                        .HasAnnotation(
                            "ModulithFoundry:TenantOwnershipProperty",
                            "OrganizationKey"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Sales.AddressRow",
                b =>
                {
                    b.HasOne("ModulithFoundry.Samples.Wholesale.Sales.CustomerRow", null)
                        .WithMany()
                        .HasForeignKey("OrganizationKey", "CustomerId")
                        .HasPrincipalKey("OrganizationKey", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
