<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../MessagingDemo/MessagingDemo.csproj" />
    <ProjectReference Include="../../src/Rootbolt.Messaging/Rootbolt.Messaging.OpenTelemetry/Rootbolt.Messaging.OpenTelemetry.csproj" />
    <ProjectReference Include="../Wholesale/ServiceDefaults/Wholesale.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
