<Project Sdk="Aspire.AppHost.Sdk/13.5.4">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>ModulithFoundry.AppHost</RootNamespace>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>959d193a-df24-4862-b1ee-39679c16e9ac</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Api/ModulithFoundry.Api.csproj" />
    <ProjectReference Include="../Migrator/ModulithFoundry.Migrator.csproj" />
  </ItemGroup>
</Project>
