// <auto-generated />
using System;
using ConsumerRoot.Catalog;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsumerRoot.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ConsumerRoot.Catalog.ItemRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TenantKey")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tenant_key");

                    b.HasKey("Id");

                    b.ToTable("items", "catalog");

                    b.HasAnnotation(
                            "ModulithFoundry:TenantContextMember",
                            "ConsumerRoot.Catalog.CatalogDbContext, FoundryApplication.Catalog, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Property|RequiredTenantKey"
                        )
                        .HasAnnotation("ModulithFoundry:TenantOwnershipFilter", "TenantScope")
                        .HasAnnotation("ModulithFoundry:TenantOwnershipProperty", "TenantKey");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
