// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Modules.Access.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Modules.Access.Persistence.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    partial class AccessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.Invitation",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("accepted_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<int>("Generation")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<byte[]>("SecretDigest")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("secret_digest");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id").HasName("pk_invitations");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_invitations_id_organization_id");

                    b.HasIndex("AcceptedByUserId")
                        .HasDatabaseName("ix_invitations_accepted_by_user_id");

                    b.HasIndex("OrganizationId", "RecipientEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_invitations_organization_pending_email")
                        .HasFilter("status = 'pending'");

                    b.ToTable("invitations", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.InvitationEmailDelivery",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("InvitationGeneration")
                        .HasColumnType("integer")
                        .HasColumnName("invitation_generation");

                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<Guid?>("LeaseId").HasColumnType("uuid").HasColumnName("lease_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProtectedPayload")
                        .HasColumnType("text")
                        .HasColumnName("protected_payload");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.HasKey("Id").HasName("pk_invitation_email_deliveries");

                    b.HasIndex("InvitationId", "OrganizationId")
                        .HasDatabaseName("ix_invitation_email_deliveries_invitation_organization");

                    b.HasIndex("OrganizationId", "InvitationId", "InvitationGeneration")
                        .IsUnique()
                        .HasDatabaseName("ux_invitation_email_deliveries_invitation_generation");

                    b.HasIndex("AvailableAt", "SentAt", "SupersededAt", "LeaseExpiresAt")
                        .HasDatabaseName("ix_invitation_email_deliveries_dispatch");

                    b.ToTable("invitation_email_deliveries", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.InvitationRoleAssignment",
                b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_id");

                    b.Property<string>("RoleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("InvitationId", "RoleId").HasName("pk_invitation_role_assignments");

                    b.HasIndex("InvitationId", "OrganizationId")
                        .HasDatabaseName("ix_invitation_roles_invitation_organization");

                    b.HasIndex("OrganizationId", "InvitationId")
                        .HasDatabaseName("ix_invitation_roles_organization_invitation");

                    b.ToTable("invitation_role_assignments", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.AccessAuditEntry",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<JsonElement>("Details")
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<short>("SchemaVersion")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_version");

                    b.Property<string>("SourceModule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_module");

                    b.Property<Guid>("SubjectId").HasColumnType("uuid").HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id").HasName("pk_audit_entries");

                    b.HasIndex("ActorUserId").HasDatabaseName("ix_audit_entries_actor_user_id");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .HasDatabaseName("ix_audit_entries_organization_occurred_at");

                    b.ToTable("audit_entries", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.Membership",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");

                    b.HasKey("Id").HasName("pk_memberships");

                    b.HasAlternateKey("Id", "OrganizationId")
                        .HasName("ak_memberships_id_organization_id");

                    b.HasIndex("UserId").HasDatabaseName("ix_memberships_user_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_memberships_organization_user")
                        .HasFilter("status IN ('active', 'suspended')");

                    b.ToTable("memberships", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.MembershipRoleAssignment",
                b =>
                {
                    b.Property<Guid>("MembershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("membership_id");

                    b.Property<string>("RoleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("MembershipId", "RoleId").HasName("pk_membership_role_assignments");

                    b.HasIndex("MembershipId", "OrganizationId")
                        .HasDatabaseName("ix_membership_roles_membership_organization");

                    b.HasIndex("OrganizationId", "MembershipId")
                        .HasDatabaseName("ix_membership_roles_organization_membership");

                    b.ToTable("membership_role_assignments", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.Organization",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id").HasName("pk_organizations");

                    b.HasIndex("Slug").IsUnique().HasDatabaseName("ux_organizations_slug");

                    b.ToTable("organizations", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Persistence.ExternalIdentityRecord",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authenticated_at");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");

                    b.HasKey("Id").HasName("pk_external_identities");

                    b.HasIndex("UserId").HasDatabaseName("ix_external_identities_user_id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_issuer_subject");

                    b.ToTable("external_identities", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Persistence.User",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id").HasName("pk_users");

                    b.ToTable("users", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.Invitation",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_invitations_users_accepted_by_user_id");

                    b.HasOne("ModulithFoundry.Modules.Access.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitations_organizations_organization_id");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.InvitationEmailDelivery",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Invitations.Invitation", null)
                        .WithMany()
                        .HasForeignKey("InvitationId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName(
                            "fk_invitation_email_deliveries_invitation_organization"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.InvitationRoleAssignment",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Invitations.Invitation", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("InvitationId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName(
                            "fk_invitation_roles_invitations_invitation_organization"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.AccessAuditEntry",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_entries_users_actor_user_id");

                    b.HasOne("ModulithFoundry.Modules.Access.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_entries_organizations_organization_id");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.Membership",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_organizations_organization_id");

                    b.HasOne("ModulithFoundry.Modules.Access.Persistence.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_memberships_users_user_id");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.MembershipRoleAssignment",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Organizations.Membership", null)
                        .WithMany("RoleAssignments")
                        .HasForeignKey("MembershipId", "OrganizationId")
                        .HasPrincipalKey("Id", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName(
                            "fk_membership_roles_memberships_membership_organization"
                        );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Persistence.ExternalIdentityRecord",
                b =>
                {
                    b.HasOne("ModulithFoundry.Modules.Access.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_users_user_id");

                    b.Navigation("User");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Invitations.Invitation",
                b =>
                {
                    b.Navigation("RoleAssignments");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Modules.Access.Organizations.Membership",
                b =>
                {
                    b.Navigation("RoleAssignments");
                }
            );
#pragma warning restore 612, 618
        }
    }
}
