// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.EventStorageDemo;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.EventStorageDemo.Migrations
{
    [DbContext(typeof(StorageDbContext))]
    [Migration("20261007203234_AddEventStreamConcurrencyStamp")]
    partial class AddEventStreamConcurrencyStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.EventStorageDemo.EventStreamRecord",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("description");

                    b.Property<string>("StreamType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stream_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable(
                        "streams",
                        "journal",
                        t =>
                        {
                            t.HasCheckConstraint("positive_stream_version", "version >= 1");
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.EventStorageDemo.StoredEventRecord",
                b =>
                {
                    b.Property<Guid>("EventId").HasColumnType("uuid").HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("StreamId").HasColumnType("uuid").HasColumnName("stream_id");

                    b.Property<long>("StreamVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("stream_version");

                    b.HasKey("EventId");

                    b.HasIndex("StreamId", "StreamVersion").IsUnique();

                    b.ToTable(
                        "facts",
                        "journal",
                        t =>
                        {
                            t.HasCheckConstraint("positive_event_schema", "schema_version >= 1");

                            t.HasCheckConstraint("positive_event_version", "stream_version >= 1");
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.EventStorageDemo.StoredEventRecord",
                b =>
                {
                    b.HasOne("ModulithFoundry.Samples.EventStorageDemo.EventStreamRecord", null)
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
