// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModulithFoundry.Samples.Wholesale.Access.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ModulithFoundry.Samples.Wholesale.Access.Persistence.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20261005204257_InitialAccess")]
    partial class InitialAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.ExternalIdentityRow",
                b =>
                {
                    b.Property<string>("Issuer")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("issuer");

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("subject");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Issuer", "Subject");

                    b.HasIndex("UserId");

                    b.ToTable("external_identities", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.MembershipRow",
                b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid").HasColumnName("id");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("organization_id");

                    b.Property<int>("Status").HasColumnType("integer").HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "UserId").IsUnique().HasFilter("status IN (1, 2)");

                    b.ToTable(
                        "memberships",
                        "access",
                        t =>
                        {
                            t.HasCheckConstraint("ck_memberships_status", "status IN (1, 2, 3)");
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.OrganizationRow",
                b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug").IsUnique();

                    b.ToTable(
                        "organizations",
                        "access",
                        t =>
                        {
                            t.HasCheckConstraint(
                                "ck_organizations_slug",
                                "slug ~ '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?$'"
                            );
                        }
                    );
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.UserRow",
                b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("users", "access");
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.ExternalIdentityRow",
                b =>
                {
                    b.HasOne("ModulithFoundry.Samples.Wholesale.Access.Persistence.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );

            modelBuilder.Entity(
                "ModulithFoundry.Samples.Wholesale.Access.Persistence.MembershipRow",
                b =>
                {
                    b.HasOne(
                            "ModulithFoundry.Samples.Wholesale.Access.Persistence.OrganizationRow",
                            null
                        )
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModulithFoundry.Samples.Wholesale.Access.Persistence.UserRow", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                }
            );
#pragma warning restore 612, 618
        }
    }
}
